server:
  port: 8080

spring:
  application:
    name: job-tracker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobtracker}
    username: postgres
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

adzuna:
    api-id: ${API_ID}
    api-key: ${API_KEY}
    url: https://api.adzuna.com/v1/api